apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-config
data:
  election-api: |
    image_repo: helpusersvote/election-api
    image_tag: de317ef949b35538d194fe462141bf3893af07f2
  go-helpusersvote: |
    image_repo: helpusersvote/go-helpusersvote
    image_tag: de317ef949b35538d194fe462141bf3893af07f2
  events-api: |
    image_repo: helpusersvote/events-api
    image_tag: de317ef949b35538d194fe462141bf3893af07f2
